### ISSUE TITLE
本番環境でMiniMagickが適応されない

### ISSUE THREAD

**Issue by takuya178** [takuya178/conve_recipe#120]
## やりたいこと

[![Image from Gyazo](https://i.gyazo.com/220df2a1d5fcffe04018a2e32e9472fe.png)](https://gyazo.com/220df2a1d5fcffe04018a2e32e9472fe)

MiniMagickでリサイズした画像をプラス一品のformに貼ってからアップロードする。

開発環境では2〜3秒程でアップロードできるが、本番環境でアップロードすると10秒以上掛かってしまう。

開発環境でのアップロード時間を短くしたい。

<br>
<br>

## 実装内容
この記事を参考に画像をリサイズしました。
[Active Storageを用いた画像読み込みが遅い問題を解決](https://qiita.com/purpleclouds0916/items/73f138a2341e7cdd19b2)

```
gem 'mini_magick'
```
```
brew install imagemagick@6
```

**mains_constoller**

```ruby
def create
   resize_image(300,300)
   @main_sub_form.save
end

private

  def resize_image(width = 300,height = 300)
    main_sub_form_params[:subs_attributes][:image].tempfile = 
    ImageProcessing::MiniMagick.source(main_sub_form_params[:subs_attributes][:image].tempfile).resize_to_fit(width, height).call
  end
```

<br>
<br>

## 考えられる原因
本番環境に対して imagemagickを再度インストールする必要があるのでは？と考えています。

[Macにrmagickをインストールする](https://qiita.com/h-sakano/items/532aabbbddab84f58307)
この記事より、私のMacだとImageMagickが7系だったので、一度ImageMagickをアンインストールしてから6系をインストールしました。
```
brew install imagemagick@6
```

```
% convert --version
Version: ImageMagick 6.9.12-29 Q16 x86_64 2021-11-14 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules 
Delegates (built-in): bzlib fontconfig freetype gslib jng jp2 jpeg lcms ltdl lzma png ps tiff webp xml zlib
```
<br>

ターミナルでImageMagick6系に入れ直したので、herokuにも6系を入れなければいけないのかなと思ったので、herokuの ImageMagickを確認したのですが6系がインストールされていました。(herokuに対して ImageMagickをインストールしたりは一切行なっていないです。)
```
% heroku run convert -version
Running convert -version on ⬢ healthy-combi2... up, run.3851 (Free)
Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib
```

```
 % heroku run magick -version
Running magick -version on ⬢ healthy-combi2... up, run.6129 (Free)
bash: magick: command not found
```

**Comment by MrFuku** [comment]
> 開発環境では2〜3秒程でアップロードできるが、本番環境でアップロードすると10秒以上掛かってしまう。

という症状の解決方法が「imagemagickの再インストール」というのが腑に落ちないのですが、なぜそう思ったのでしょうか？
単純にネットワークやCPUリソースの問題という線はないのでしょうか？

**Comment by takuya178** [comment]
お疲れ様です。
ImageProcessing::MiniMagickのコードが間違えていただけで無事解決できました。
ありがとうございました。
