### ISSUE TITLE
herokuドメイン設定のエラー

### ISSUE THREAD

**Issue by takuya178** [takuya178/conve_recipe#135]
# やりたいこと
herokuでドメインを追記しようとするとエラーが表示されるので解決したいです。

実装手順は以下の記事を参考にしました。
[お名前.comを使い、独自ドメイン取得し、herokuデプロイする](https://qiita.com/tksh8/items/ab3748bcb01316461abe)

herokuはドメイン名を追加するためHobbyプランに変更し。お名前ドットコムで「healthy-combi.com」というドメインを購入しました。
[![Image from Gyazo](https://i.gyazo.com/1e35140512e67b3df891eb79a19e08f0.png)](https://gyazo.com/1e35140512e67b3df891eb79a19e08f0)

<br>

# エラー内容

Add domainでドメイン名を追加するとエラーが表示される。
[![Image from Gyazo](https://i.gyazo.com/23689abc5839036e2652390bdc0f2118.png)](https://gyazo.com/23689abc5839036e2652390bdc0f2118)

[![Image from Gyazo](https://i.gyazo.com/ab214d93797266a418c65bf82765bb0b.png)](https://gyazo.com/ab214d93797266a418c65bf82765bb0b)

```ruby
conve_recipe % heroku certs:auto       
=== Automatic Certificate Management is enabled on healthy-combi

Domain                 Status   Reason                                           Last Updated
─────────────────────  ───────  ───────────────────────────────────────────────  ──────────────────
www.healthy-combi.com  Failing  Unable to resolve DNS for www.healthy-combi.com  less than a minute
=== Some domains are failing validation, please verify that your DNS matches: heroku domains
    See our documentation at https://devcenter.heroku.com/articles/automated-certificate-management#failure-reasons
```

ACMを有効にするため以下のコマンドを実行したが結果は変わらずでした。
```ruby
heroku certs:auto:enable
```

**Comment by takuya178** [comment]
[![Image from Gyazo](https://i.gyazo.com/8345777b824b850ac61cd99c56275dc2.png)](https://gyazo.com/8345777b824b850ac61cd99c56275dc2)

**Comment by takuya178** [comment]
issueに記載したqiitaの記事を参考にしたので、TTLに関してはデフォルトの3600で設定しました。（特に理由なく設定してしまいました。）VALUEはherokuでドメインを作成した時のDNS Targetをコピーして値を入れました。

**Comment by takuya178** [comment]
[![Image from Gyazo](https://i.gyazo.com/8f7bbfe0698aa1c6d11b632eaf7e3c2a.png)](https://gyazo.com/8f7bbfe0698aa1c6d11b632eaf7e3c2a)

**Comment by takuya178** [comment]
VALLUEに記載されているDNS Targetの全文です。
current-mongoose-4fm4danku7fyae3fsayjgpnn.herokudns.com

**Comment by yuji91** [comment]
お名前.comでアカウントが凍結されているケースもあるようなので、お名前.comのダッシュボードで何か通知やアカウントのステータスを問題ないか確認頂きたいです。

また設定してから反映まで最長72時間ほどかかるようなので、いつ頃設定されたか覚えていれば教えて頂きたいです。

**Comment by takuya178** [comment]
[![Image from Gyazo](https://i.gyazo.com/4cd2d1faf3f3f05f36508c2a5ba624cc.png)](https://gyazo.com/4cd2d1faf3f3f05f36508c2a5ba624cc)
利用ドメイン一覧をクリックして中身を確認

<br>
<br>



[![Image from Gyazo](https://i.gyazo.com/faca1b531c9417264ee11e7deaf1f659.png)](https://gyazo.com/faca1b531c9417264ee11e7deaf1f659)
利用制限中をクリック

[![Image from Gyazo](https://i.gyazo.com/ac7a3474025af1ac2c8a3e83e8084f5b.png)](https://gyazo.com/ac7a3474025af1ac2c8a3e83e8084f5b)

<br>
<br>

ドメインは昨日（約30時間前）に設定しました。昨日Herokuからdomainがないとのメールがあり。
[![Image from Gyazo](https://i.gyazo.com/ce8116ecf095d3f8acc2e0c8bacc659d.png)](https://gyazo.com/ce8116ecf095d3f8acc2e0c8bacc659d)

**Comment by DaichiSaito** [comment]
利用制限中と書いてあるのでかなり怪しいですね！ちょっと調べてみてください！
![image](https://user-images.githubusercontent.com/10973259/145028645-3657408c-968e-4da8-ad25-5f6b2d7edeb7.png)

**Comment by takuya178** [comment]
お疲れ様です。
調べたところお名前.comでメールアドレス有効性確認の手続きが確認できていないことが原因でした。この手続きを完了したところステータスが起動中になり、アプリも無事https対応になりました。色々ご指摘いただきありがとうございました。
[![Image from Gyazo](https://i.gyazo.com/b11b93215bf538ff6d83322f66ca0f9b.png)](https://gyazo.com/b11b93215bf538ff6d83322f66ca0f9b)

[![Image from Gyazo](https://i.gyazo.com/6fdf67b3e88d05b14daa2f60f3ebfc71.jpg)](https://gyazo.com/6fdf67b3e88d05b14daa2f60f3ebfc71)
